rabbitmq:
  image: tutum/rabbitmq
  environment:
    RABBITMQ_USER: NI4EvqdOy3RT
    RABBITMQ_PASS: aEW5qDg3qPBh
  restart: always

redis:
  image: tutum/redis
  environment:
    REDIS_PASS: WQuxUloeZomF
  restart: always

server:
  image: hmrc/sensu-server:1.9
  links:
    - rabbitmq
    - redis
  restart: always

client:
  image: hmrc/sensu-client:1.9
  links:
    - rabbitmq
  environment:
    # Specify Sensu subscriptions for the client as a CSV string
    SUBSCRIPTIONS: development,web
  restart: always

api:
  image: hmrc/sensu-api:1.9
  links:
    - rabbitmq
    - redis
  environment:
    API_USER: 2RXlri2xmx5i
    API_PASS: jrHVKNuM8Zw4
  restart: always

uchiwa:
  image: hmrc/uchiwa:1.4.1
  links:
    - api
  ports:
    - 3000:80
  environment:
    HTTP_USER: hiro
    HTTP_PASS: nakamura
  restart: always
